import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navbarItems = [
  { id: 1, name: "Home", url: "/", icon: "home", active: true },
  { id: 2, name: "Dashboards", url: "/dashboards", icon: "dashboard" },
  { id: 3, name: "Segments", url: "/segments", icon: "segments" },
  { id: 4, name: "Account", url: "/account", icon: "account" },
  { id: 5, name: "Settings", url: "/settings", icon: "settings" },
];
const footerItems = [
  { id: 1, name: "Conditions of Use", url: "/conditions-of-use" },
  { id: 2, name: "Privacy Notice", url: "/privacy" },
  { id: 3, name: "Interest-Based Ads", url: "/interest-based-ads" },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Navbar data={navbarItems} />
        {children}
        <Footer list={footerItems} />
      </body>
    </html>
  );
}
